server:
  port: 8084
  
 
 
spring:
    application:
        name: API-GATEWAY
        
 
    cloud:
      discovery:
        enabled: true
      gateway:
        discovery:
           locator:
              lower-case-service-id: true
              enabled: true
        routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
          - Path=/users/**
          filters:
           - AuthenticationFilter
          
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
          - Path=/hotels/**
          filters:
           - AuthenticationFilter
        
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
          - Path=/ratings/**
          filters:
           - AuthenticationFilter
        
        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
          - Path=/auth/**
     
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true             
    
