server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: ankitdb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
   
  config:
    import: optional:configserver:http://localhost:8085
  profiles:
    active: default
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
#    register-with-eureka: true       